//! Solidity verifier contract generation.
//!
//! This module generates Solidity smart contracts for on-chain verification
//! of Groth16 proofs. The generated contracts are optimized for gas efficiency
//! and follow best practices for security.
//!
//! # Usage
//!
//! ```ignore
//! use acvm_backend_groth16::solidity::SolidityVerifierGenerator;
//!
//! let generator = SolidityVerifierGenerator::new();
//! let contract = generator.generate(&verification_key)?;
//!
//! // Save to file
//! std::fs::write("Verifier.sol", contract)?;
//! ```

use crate::errors::ContractGenerationError;
use crate::keys::Groth16VerificationKey;
use ark_bn254::{Bn254, Fq, G1Affine, G2Affine};
use ark_ec::AffineRepr;
use ark_ff::{BigInteger, PrimeField};
use num_bigint::BigUint;

/// Generator for Solidity verifier contracts.
pub struct SolidityVerifierGenerator {
    /// Name of the generated contract.
    contract_name: String,
}

impl Default for SolidityVerifierGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl SolidityVerifierGenerator {
    /// Creates a new Solidity verifier generator with default settings.
    pub fn new() -> Self {
        Self {
            contract_name: "Groth16Verifier".to_string(),
        }
    }

    /// Sets the contract name.
    pub fn with_contract_name(mut self, name: impl Into<String>) -> Self {
        self.contract_name = name.into();
        self
    }

    /// Generates a Solidity verifier contract for the given verification key.
    ///
    /// Currently only supports BN254 curve.
    ///
    /// # Arguments
    /// * `vk` - The Groth16 verification key
    ///
    /// # Returns
    /// The generated Solidity contract as a string, or an error
    pub fn generate(
        &self,
        vk: &Groth16VerificationKey<Bn254>,
    ) -> Result<String, ContractGenerationError> {
        let vk_inner = &vk.key;

        // Extract verification key components
        let alpha_g1 = format_g1_point(&vk_inner.alpha_g1)?;
        let beta_g2 = format_g2_point(&vk_inner.beta_g2)?;
        let gamma_g2 = format_g2_point(&vk_inner.gamma_g2)?;
        let delta_g2 = format_g2_point(&vk_inner.delta_g2)?;

        // Format IC (public input commitment) points
        let ic_points: Result<Vec<String>, _> = vk_inner
            .gamma_abc_g1
            .iter()
            .map(|p| format_g1_point(p))
            .collect();
        let ic_points = ic_points?;

        let num_public_inputs = vk.num_public_inputs;

        // Generate the contract
        let contract = self.render_contract(
            &alpha_g1,
            &beta_g2,
            &gamma_g2,
            &delta_g2,
            &ic_points,
            num_public_inputs,
        );

        Ok(contract)
    }

    fn render_contract(
        &self,
        alpha_g1: &str,
        beta_g2: &str,
        gamma_g2: &str,
        delta_g2: &str,
        ic_points: &[String],
        num_public_inputs: usize,
    ) -> String {
        let ic_assignments = ic_points
            .iter()
            .enumerate()
            .map(|(i, p)| format!("        vk.IC[{}] = Pairing.G1Point({});", i, p))
            .collect::<Vec<_>>()
            .join("\n");

        format!(
            r#"// SPDX-License-Identifier: MIT
// Generated by acvm-backend-groth16
// WARNING: This contract is auto-generated. Do not modify manually.

pragma solidity ^0.8.0;

library Pairing {{
    struct G1Point {{
        uint256 X;
        uint256 Y;
    }}

    struct G2Point {{
        uint256[2] X;
        uint256[2] Y;
    }}

    /// @return the generator of G1
    function P1() internal pure returns (G1Point memory) {{
        return G1Point(1, 2);
    }}

    /// @return the generator of G2
    function P2() internal pure returns (G2Point memory) {{
        return G2Point(
            [11559732032986387107991004021392285783925812861821192530917403151452391805634,
             10857046999023057135944570762232829481370756359578518086990519993285655852781],
            [4082367875863433681332203403145435568316851327593401208105741076214120093531,
             8495653923123431417604973247489272438418190587263600148770280649306958101930]
        );
    }}

    /// @return r the negation of p, i.e. p.addition(p.negate()) should be zero.
    function negate(G1Point memory p) internal pure returns (G1Point memory r) {{
        // The prime q in the base field F_q for G1
        uint256 q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
        if (p.X == 0 && p.Y == 0) {{
            return G1Point(0, 0);
        }}
        return G1Point(p.X, q - (p.Y % q));
    }}

    /// @return r the sum of two points of G1
    function addition(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {{
        uint256[4] memory input;
        input[0] = p1.X;
        input[1] = p1.Y;
        input[2] = p2.X;
        input[3] = p2.Y;
        bool success;
        assembly {{
            success := staticcall(sub(gas(), 2000), 6, input, 0xc0, r, 0x60)
        }}
        require(success, "pairing-add-failed");
    }}

    /// @return r the product of a point on G1 and a scalar, i.e.
    /// p == p.scalar_mul(1) and p.addition(p) == p.scalar_mul(2) for all points p.
    function scalar_mul(G1Point memory p, uint256 s) internal view returns (G1Point memory r) {{
        uint256[3] memory input;
        input[0] = p.X;
        input[1] = p.Y;
        input[2] = s;
        bool success;
        assembly {{
            success := staticcall(sub(gas(), 2000), 7, input, 0x80, r, 0x60)
        }}
        require(success, "pairing-mul-failed");
    }}

    /// @return the result of computing the pairing check
    /// e(p1[0], p2[0]) * ... * e(p1[n], p2[n]) == 1
    function pairing(G1Point[] memory p1, G2Point[] memory p2) internal view returns (bool) {{
        require(p1.length == p2.length, "pairing-lengths-failed");
        uint256 elements = p1.length;
        uint256 inputSize = elements * 6;
        uint256[] memory input = new uint256[](inputSize);
        for (uint256 i = 0; i < elements; i++) {{
            input[i * 6 + 0] = p1[i].X;
            input[i * 6 + 1] = p1[i].Y;
            input[i * 6 + 2] = p2[i].X[0];
            input[i * 6 + 3] = p2[i].X[1];
            input[i * 6 + 4] = p2[i].Y[0];
            input[i * 6 + 5] = p2[i].Y[1];
        }}
        uint256[1] memory out;
        bool success;
        assembly {{
            success := staticcall(sub(gas(), 2000), 8, add(input, 0x20), mul(inputSize, 0x20), out, 0x20)
        }}
        require(success, "pairing-opcode-failed");
        return out[0] != 0;
    }}

    /// Convenience method for a pairing check for four pairs.
    function pairingProd4(
        G1Point memory a1, G2Point memory a2,
        G1Point memory b1, G2Point memory b2,
        G1Point memory c1, G2Point memory c2,
        G1Point memory d1, G2Point memory d2
    ) internal view returns (bool) {{
        G1Point[] memory p1 = new G1Point[](4);
        G2Point[] memory p2 = new G2Point[](4);
        p1[0] = a1;
        p1[1] = b1;
        p1[2] = c1;
        p1[3] = d1;
        p2[0] = a2;
        p2[1] = b2;
        p2[2] = c2;
        p2[3] = d2;
        return pairing(p1, p2);
    }}
}}

contract {contract_name} {{
    using Pairing for *;

    struct VerifyingKey {{
        Pairing.G1Point alpha1;
        Pairing.G2Point beta2;
        Pairing.G2Point gamma2;
        Pairing.G2Point delta2;
        Pairing.G1Point[] IC;
    }}

    struct Proof {{
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }}

    function verifyingKey() internal pure returns (VerifyingKey memory vk) {{
        vk.alpha1 = Pairing.G1Point({alpha_g1});
        vk.beta2 = Pairing.G2Point({beta_g2});
        vk.gamma2 = Pairing.G2Point({gamma_g2});
        vk.delta2 = Pairing.G2Point({delta_g2});
        vk.IC = new Pairing.G1Point[]({ic_len});
{ic_assignments}
    }}

    function verify(uint256[] memory input, Proof memory proof) internal view returns (bool) {{
        uint256 snark_scalar_field = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        VerifyingKey memory vk = verifyingKey();
        require(input.length + 1 == vk.IC.length, "verifier-bad-input");
        // Compute the linear combination vk_x
        Pairing.G1Point memory vk_x = Pairing.G1Point(0, 0);
        for (uint256 i = 0; i < input.length; i++) {{
            require(input[i] < snark_scalar_field, "verifier-gte-snark-scalar-field");
            vk_x = Pairing.addition(vk_x, Pairing.scalar_mul(vk.IC[i + 1], input[i]));
        }}
        vk_x = Pairing.addition(vk_x, vk.IC[0]);
        return Pairing.pairingProd4(
            Pairing.negate(proof.A), proof.B,
            vk.alpha1, vk.beta2,
            vk_x, vk.gamma2,
            proof.C, vk.delta2
        );
    }}

    /// @return r bool true if proof is valid
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[{num_public_inputs}] memory input
    ) public view returns (bool r) {{
        Proof memory proof;
        proof.A = Pairing.G1Point(a[0], a[1]);
        proof.B = Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]);
        proof.C = Pairing.G1Point(c[0], c[1]);
        uint256[] memory inputValues = new uint256[]({num_public_inputs});
        for (uint256 i = 0; i < {num_public_inputs}; i++) {{
            inputValues[i] = input[i];
        }}
        return verify(inputValues, proof);
    }}
}}
"#,
            contract_name = self.contract_name,
            alpha_g1 = alpha_g1,
            beta_g2 = beta_g2,
            gamma_g2 = gamma_g2,
            delta_g2 = delta_g2,
            ic_len = ic_points.len(),
            ic_assignments = ic_assignments,
            num_public_inputs = num_public_inputs,
        )
    }
}

/// Formats a G1 point for Solidity.
fn format_g1_point(point: &G1Affine) -> Result<String, ContractGenerationError> {
    if point.is_zero() {
        return Ok("0, 0".to_string());
    }

    let x = format_fq(&point.x);
    let y = format_fq(&point.y);

    Ok(format!("{}, {}", x, y))
}

/// Formats a G2 point for Solidity.
fn format_g2_point(point: &G2Affine) -> Result<String, ContractGenerationError> {
    if point.is_zero() {
        return Ok("[0, 0], [0, 0]".to_string());
    }

    let x0 = format_fq(&point.x.c0);
    let x1 = format_fq(&point.x.c1);
    let y0 = format_fq(&point.y.c0);
    let y1 = format_fq(&point.y.c1);

    Ok(format!("[{}, {}], [{}, {}]", x0, x1, y0, y1))
}

/// Formats a field element as a decimal string.
fn format_fq(fq: &Fq) -> String {
    let bigint = fq.into_bigint();
    let bytes = bigint.to_bytes_be();
    let num = BigUint::from_bytes_be(&bytes);
    num.to_string()
}

/// Formats a Groth16 proof for Solidity verification.
///
/// Returns a tuple of (a, b, c) formatted for the verifyProof function.
pub fn format_proof_for_solidity(
    proof: &crate::proof::Groth16Proof<Bn254>,
) -> Result<(String, String, String), ContractGenerationError> {
    let a = &proof.proof.a;
    let b = &proof.proof.b;
    let c = &proof.proof.c;

    let a_str = format!(
        "[{}, {}]",
        format_fq(&a.x),
        format_fq(&a.y)
    );

    let b_str = format!(
        "[[{}, {}], [{}, {}]]",
        format_fq(&b.x.c0),
        format_fq(&b.x.c1),
        format_fq(&b.y.c0),
        format_fq(&b.y.c1)
    );

    let c_str = format!(
        "[{}, {}]",
        format_fq(&c.x),
        format_fq(&c.y)
    );

    Ok((a_str, b_str, c_str))
}

/// Formats public inputs for Solidity verification.
pub fn format_public_inputs_for_solidity(
    inputs: &crate::proof::PublicInputs<ark_bn254::Fr>,
) -> Vec<String> {
    inputs
        .values
        .iter()
        .map(|v| {
            let bigint = v.into_bigint();
            let bytes = bigint.to_bytes_be();
            let num = BigUint::from_bytes_be(&bytes);
            num.to_string()
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_fq() {
        // Test with a simple value
        let fq = Fq::from(12345u64);
        let formatted = format_fq(&fq);
        assert_eq!(formatted, "12345");
    }
}
